##Word Params###
BLOCKS_DIMENSION = (21,23) #ROWS,COLUMNS

GRID_WIDTH = 1
TITLE = "Algo PlayGround"
ALGORITHM_TITLE = ""
MOVEMENT_SPEED = 10
BOTTOM_PANEL_HEIGHT = 200 #Size of bottom panel for control
MARGIN = 15 #Margin between sides and the grid


###Colors###
DARK_PURPLE = (3, 3, 66)
GRAY = (232, 232, 232)
DARK_GRAY = (130, 130, 130)
LIGHT_BLUE = (217, 247, 255)
BROWN = (61, 51, 23)
WHITE = (255,255,255)
BLUE = (14, 113, 143)
BLACK = (0,0,0)
GREEN = (151, 240, 175)
RED = (255, 120, 120)
BACKGROUND_COLOR = WHITE
GRID_COLOR = GRAY
BLOCK_COLOR = BROWN
START_NODE_COLOR = DARK_PURPLE
HIGHLIGHT_COLOR = DARK_GRAY


BUTTON_COLOR_PRIMARY = BROWN
BUTTON_COLOR_SECONDARY = BLUE
SELECTED_NODE_COLOR = RED

INFO_LABEL_COLOR = DARK_GRAY


###Block Size###
BLOCK_SIZE = 30
###Node Size###
NODE_SIZE = 30
NODE_BORDER_COLOR = BLACK
NODE_COLOR = GRAY
SPECIAL_NODE_BORDER_COLOR = DARK_PURPLE
SPECIAL_NODE_COLOR = GREEN


###UI ELEMENTS###
INPUT_HEIGHT = 30
INPUT_WIDTH = 150


###FILE RESOURCES###
MY_WORK_DIR = "MyGraph/" #Directory in which the work is saved


